name: Run tests
on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'

