name: Run tests
on:
  pull_request:
    types: [opened]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn

      - name: Sync version
        run: node .github/actions/sync-version.js

      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Sync version with dependency" || exit 0
          git push
