name: Sync version with Lucide
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      # Setup node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn

      - name: Sync version
        run: node .github/actions/sync-version.js

      - name: Update the lockfile
        run: yarn

      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Sync version with dependency" || exit 0
          git push
