name: Release and Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.released }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish to npm
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#  create-release:
#    name: Create Release
#    runs-on: ubuntu-latest
#    outputs:
#      released: ${{ steps.release.outputs.released }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Automatic GitHub Release
#        uses: justincy/github-action-npm-release@2.0.2
#        id: release
#      - name: Print release output
#        if: ${{ steps.release.outputs.released == 'true' }}
#        run: echo Release ID ${{ steps.release.outputs.release_id }}
#
#  publish-package:
#    name: Publish to NPM
#    needs: [create-release]
#    if: needs.create-release.outputs.released == 'true'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout project
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.head_ref }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Setup node
#        uses: actions/setup-node@v3
#        with:
#          cache: 'yarn'
#          node-version: 16
#          registry-url: https://registry.npmjs.org
#
#      - name: Install dependencies
#        run: yarn
#
#      - name: Build project
#        run: yarn build
#
#      - name: Run tests
#        run: yarn test
#
#      - name: Publish to npm
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
