name: Release and Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}
      - name: Setup node
        if: steps.release.outputs.released == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        if: steps.release.outputs.released == 'true'
        run: yarn
      - name: Build project
        if: steps.release.outputs.released == 'true'
        run: yarn build
      - name: Run tests
        if: steps.release.outputs.released == 'true'
        run: yarn test
      - name: Publish to npm
        if: steps.release.outputs.released == 'true'
        run: rm package.json && rm yarn.lock && cd dist && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
