name: Run tests
on:
  pull_request:
    types:
      - labeled
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: github.event.label.name == 'version in sync' # Ensuring it's the "Needs Review" label
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: yarn
      - run: yarn generate
      - run: yarn test

name: Run tests
on:
  pull_request:
    types:
      - labeled
